### PR TITLE
Added Floating Text.

### LINKED ISSUE #245: [REQUEST] Floating damage numbers
The players often felt frustrated at the lack of indicators of damage upon the enemies. To solve this, an indicator of damage must appear above the object of impact.

**Describe the solution you'd like**
A number showing how much damage was done will appear above the object that was hit, appearing a small number in white text that fades after 1 second.

### PR DESCRIPTION
**Pull request by 100575155**
## Summary
Added floating text to projectiles that play when it hits something.

## Linked Issues
closes #245

### CODE REVIEW

**Review by MistaMishMash — COMMENTED** [review]
Just playtested this, and it looks awesome !!! I love the little animation!
I have 2 suggestions:

1: putting the ShowDamage methods in Projectile means that it won't take any damage reductions into account (eg, if the ships have damage reduction plating on them) So might be better to put it into the asteroid's and ship's TakeDamage method?  Please correct me if I am wrong here though!
I think you could still draw it at the same location, as the ProjectileEntity is passed to that method.
If you did end up moving the logic, consider using the CombatHUD to put the ShowDamage text in. Up to you of course though!

2: the white damage text is a little difficult to see when asteroids are exploding (as it's white on white). A resolution to this would be awesome, but up to you. Could leave this as an extension task later if you wanted, just thought I should flag it and let you know.

**Comment by MistaMishMash** [comment]
Oh also, the current logic won't (I believe) show collision damage, or damage over time (See DamageOverTimeSystem.cs)
Moving it to .TakeDamage, perhaps in entity, would fix this.

**Review by MistaMishMash — APPROVED** [review]
Have playtested with collision, projectile, and damage over time, and all seem to be working great! (I might need to fix some bugs in DoT too >> )
Hope the changes weren't too much trouble, looks good c:

**Comment by Liam-Harrison** [comment]
The changes look good, but this PR was out of date and it has some strange merge conflicts with other changes that were merged into main from your existing branch. Will merge in once it has been rebased and the merge conflicts in the scripts have been resolved.

**Pull request merged**
