### PR TITLE
Added on-hit and on-destroy graphical effect triggers

### LINKED ISSUE #181: [REQUEST] Collision particle effects trigger
When the ship collides with objects, particle effects should kick in displaying a collision in the form of sparks, or a small explosion, or burst of fire, etc.

This task is complete when a collision between the ship, another enemy ship, asteroid, or any other game object, creates a trigger for particle effects.

### PR DESCRIPTION
**Pull request by MistaMishMash**
## Summary
Added a trigger to all entities, such that they may have on-hit and on-destroy effects, so Lachlan can add said effects.
I also cleaned up weapon data, so only shrapnel, autocannon and a placeholder for charge weapon exists. This means that the small enemy ships all have autocannons you can see on their hulls now, I hope that is ok ! (Assumed this was the intended functionality anyway).

## Linked Issues
Closes #181 

## Screenshots (optional)
image
Above shows the inspector interface, where you can specify on-hit effects and on-destroy effects, along with how long the effect should last for (in seconds)

### CODE REVIEW

**Comment by TeaRussell** [comment]
\o/

**Comment by TeaRussell** [comment]
Shit sorry I was trying to tick an approvey thingy but I don't have one and it just... closed it... sorry ._.

**Comment by TeaRussell** [comment]
Also this closes #186

**Review by Liam-Harrison — APPROVED** [review]
Very good 👍

**Pull request merged**
